apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYWJkZWxsYWg4bWFzc2FkIiwicGFzc3dvcmQiOiJnaXRodWJfcGF0XzExQUZUWTdXUTBQY0x1a1VMQ0FYQnJfWkxxQlJwa3dSVG1Kc0N4YXp6aGdQUUd4R0pnczAwVm9veE43ZVp6RHhZUUNDWk1KVVJYYWpjdEN2dFAiLCJhdXRoIjoiWVdKa1pXeHNZV2c0YldGemMyRmtPbWRwZEdoMVlsOXdZWFJmTVRGQlJsUlpOMWRSTUZCalRIVnJWVXhEUVZoQ2NsOWFUSEZDVW5CcmQxSlViVXB6UTNoaGVucG9aMUJSUjNoSFNtZHpNREJXYjI5NFRqZGxXbnBFZUZsUlEwTmFUVXBWVWxoaGFtTjBRM1owVUE9PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
